# prek.toml
default_install_hook_types = ["pre-commit", "commit-msg"]

[[repos]]
repo = "builtin"
hooks = [
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "check-merge-conflict" },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-fmt"
name = "cargo fmt"
entry = "cargo fmt --all "
language = "system"
types = ["rust"]
pass_filenames = false

[[repos.hooks]]
id = "cargo-clippy"
name = "cargo clippy"
entry = "cargo clippy --workspace --all-targets --all-features -- -D warnings"
language = "system"
types = ["rust"]
pass_filenames = false

[[repos.hooks]]
id = "commitlint"
name = "commitlint"
entry = "commitlint --edit"
language = "system"
stages = ["commit-msg"]
pass_filenames = false

[[repos.hooks]]
id = "taplo-fmt"
name = "taplo fmt"
entry = "taplo fmt"
language = "system"
types = ["toml"]
pass_filenames = false

[[repos.hooks]]
id = "taplo-lint"
name = "taplo lint"
entry = "taplo lint"
language = "system"
types = ["toml"]
pass_filenames = false

[[repos.hooks]]
id = "typos"
name = "typos"
entry = "typos"
language = "system"
pass_filenames = false
